### ISSUE TITLE
Program crashes after redeeming one code

### ISSUE THREAD

**Issue by brothan323** [Lumbridge/SmiteMixerCodeRedeemer#38]
WHY!>!>!>!>!>??!?!? I have missed EVERY SINGLE mixer game this weekend because this stupid program crashes:\ I cannot figure out why it crashes because I sleep while it's on, I'm not up during these mixer games.

This is beyond annoying.

**Comment by brothan323** [comment]
Edit: I'm always in AFK mode and I have a dual monitor set up. I think your program doesn't like dual monitors, and that's not actually bringing up the SMITE program to the foreground, it's bring what-ever program to the foreground on whatever screen was selected last.

**Comment by kaimi** [comment]
> Edit: I'm always in AFK mode and I have a dual monitor set up. I think your program doesn't like dual monitors, and that it's not actually bringing up the SMITE program to the foreground, it brings whatever program to the foreground on whatever screen was selected last.

It works just fine for me with 2 and 3 monitors.

**Comment by Lumbridge** [comment]
No attempt at giving any useful info/reproduction of the issue, generally bad attitude, sending me BM private messages; if you want my help then you’re going about it the wrong way. Closed.

Note: you don’t need the mixer stream running for the program to work; if anything it’ll hinder the program if your machine is rather low spec (assuming here because you give no information).
